name: autoescuelaslavega
favicon: null
layout_spectrum: 0.86188
typography_spectrum: 0.7194474840071052
title: Autoescuelas La Vega Nonduermas Murcia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a18'
    - '#ff8041'
    - '#ffffff'
    - '#767674'
    - '#a3a3a3'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5906424610875547
purpose: []
