name: autoescuelaslavega
favicon: null
layout_spectrum: 0.57445
typography_spectrum: 0.31498
title: 'Autoescuelas La Vega -Nonduermas, Murcia-'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#fe5709'
    - '#56565a'
    - '#98979b'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
