name: autoescuelaslavega
favicon: null
layout_spectrum: 0.5943071045912802
typography_spectrum: 0.7194474840071052
title: Autoescuelas La Vega Nonduermas Murcia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a18'
    - '#ff8041'
    - '#ffffff'
    - '#767674'
    - '#a3a3a3'
  brandStrength: 0.4315308863297105
  lightness: 0.3391495996620506
  saturation: 0.25927353743463755
  rhythmicContrast: 0.5906424610875547
purpose: []
