name: autoescuelaslavega
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31498
title: Autoescuelas La Vega
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffae8'
    - '#c1baa8'
    - '#6c6553'
    - '#0d0200'
    - '#3a3221'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
